name: Deploy ServicePortaal Next.js to DreamHost VPS

on:
    # Runs on pushes targeting the default branch
    push:
        branches: [ "development" ]

    # Runs on pull request targeting the default branch
    pull_request:
        branches: [ "development" ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    # Build and Deploy job
    build_and_deploy:
        name: Build and Deploy Next.js App
        runs-on: ubuntu-latest

        steps:
            # Step 1: Check out the repository
            -   name: Checkout repository
                uses: actions/checkout@v4

            # Step 2: Set up Node.js
            -   name: Setup Node
                uses: actions/setup-node@v4
                with:
                    node-version: "latest"
                    cache: 'npm'

            # Step 3: Install dependencies
            -   name: Install dependencies
                run: npm install

            # Step 4: Build the Next.js app
            -   name: Build Next.js app
                run: npm run build

            # Step 5: Clean up the old files on DreamHost VPS
            -   name: Cleanup old files on DreamHost VPS
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USERNAME }}
                    password: ${{ secrets.SSH_PASSWORD }}
                    port: "22"
                    script: |
                        rm -rf ~/serviceportaal.be/*

            # Step 6: Deploy files to DreamHost VPS
            -   name: Deploy to DreamHost VPN
                uses: appleboy/scp-action@master
                with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USERNAME }}
                    password: ${{ secrets.SSH_PASSWORD }}
                    port: "22"
                    source: "."
                    target: "~/serviceportaal.be"

            # Extra Step First Time
            -   name: Install NVM, Node.js, npm, and pm2
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USERNAME }}
                    password: ${{ secrets.SSH_PASSWORD }}
                    port: "22"
                    script: |
                        if [ ! -d "$HOME/.nvm" ]; then
                            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
                        fi
                        
                        export NVM_DIR="$HOME/.nvm"
                        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                        
                        nvm install node
                        nvm use node
                        nvm alias default node
                        
                        $NVM_DIR/versions/node/$(nvm current)/bin/npm install -g pm2

            # Step 7: Install dependencies and start/restart the Node.js app using pm2
            -   name: Restart Node.js app on DreamHost VPS
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USERNAME }}
                    password: ${{ secrets.SSH_PASSWORD }}
                    port: "22"
                    script: |
                        cd ~/serviceportaal.be
                        npm install
                        pm2 stop all || true
                        pm2 start npm --name "serviceportaal" -- start -- -p 3000